ImgResize/ImgResize/urls.py
from django.contrib import admin
from django.urls import path, include
from webapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('webapp.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ImgResize/webapp/urls.py
from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
]

ImgResize/webapp/models.py
from django.db import models


# Create your models here.
class Images(models.Model):
    #can save the image in this database, if code was written to handle file uploads from JS code, then uncomment this and make sure that the fields are met when saving. 
    img = models.ImageField(upload_to = 'images/')
    # sImg = models.ImageField(upload_to = 'images/sreduced/',blank = True, null = True)       # reduced by 3/4
    # xsImg = models.ImageField(upload_to = 'images/xsreduced/',blank = True,null = True)      # reduced by 1/2
    # xxsImg = models.ImageField(upload_to = 'images/xxsreduced/',blank = True,null = True)    # reduced by 1/4

ImgResize/webapp/forms.py
from django import forms
from .models import *

class ImageForm(forms.ModelForm):
    class Meta:
        model = Images
        fields = ['img']

ImgResize/webapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import *
from .models import *
# from django.core.files import File
# from io import StringIO,BytesIO 
# import io
from PIL import Image
# Create your views here.
def index (request):
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            #this is for when you're going to save images to the server
            form.save()
            return redirect('index')
    else:
        form = ImageForm()
        return render(request, 'webapp/index.html', {'form': form})

ImgResize/webapp/templates/webapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Image Upload</title>
</head>
<body>
    <form id = "id_form" method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.img }}
        </br>
        </br>
        <button type = "button" onclick ="process()">Upload</button>
    </form>
    <div>
        <img id = "input"/>
    </div>
    <div>
        <h3 id = "h3a" style = "display:none;">720p</h3><br>
        <img id = "output"/>
    </div>
    <div >
        <h3 id = "h3b" style = "display:none;">480p</h3><br>
        <img id = "output2"/>
    </div>
    <div>
        <h3 id = "h3c" style = "display:none;">360p</h3><br>
        <img id = "output3"/>
    </div>

    <!-- https://www.youtube.com/watch?v=bXf_UdyDzSA&ab_channel=CodingShikshaCodingShiksha -->
    <!-- code for this script was based off this video, updated to work with multiple image files -->
    <script>
        function process(){
        const file = document.querySelector("#id_img").files[0];
        if(!file) return;
        
        const reader = new FileReader();
    
        reader.readAsDataURL(file);
    
        reader.onload = function(event){
            const imgElement = document.createElement("img");
            const imgElement2 = document.createElement("img");
            const imgElement3 = document.createElement("img");

            imgElement.src = event.target.result;
            imgElement2.src = event.target.result;
            imgElement3.src = event.target.result;
            
            document.querySelector("#input").src = event.target.result;

            imgElement.onload = function(e){
                const canvas = document.createElement("canvas");
                
                // resizing to 720p
                const MAX_WIDTH = 1280;
                const scaleSize = MAX_WIDTH / e.target.width;
                canvas.width = MAX_WIDTH;
                canvas.height = e.target.height * scaleSize;
                //output 720p image
                const ctx = canvas.getContext('2d');
                ctx.drawImage(e.target, 0, 0, canvas.width, canvas.height);
                const srcEncoded = ctx.canvas.toDataURL(e.target, "image/png");
                document.querySelector("#output").src = srcEncoded;
                document.getElementById("h3a").style.display = "inline";
                console.log(srcEncoded);
            };
            imgElement2.onload = function(e){
                
                const canvas = document.createElement("canvas");
                
                // resizing to 480p
                const MAX_WIDTH = 854;
                const scaleSize = MAX_WIDTH / e.target.width;
                canvas.width = MAX_WIDTH;
                canvas.height = e.target.height * scaleSize;
                //output 480p image
                const ctx = canvas.getContext('2d');
                ctx.drawImage(e.target, 0, 0, canvas.width, canvas.height);
                const srcEncoded = ctx.canvas.toDataURL(e.target, "image/png");
                document.querySelector("#output2").src = srcEncoded;

                document.getElementById("h3b").style.display = "inline";

            };
            imgElement3.onload = function(e){
                
                const canvas = document.createElement("canvas");
                
                // resizing to 320p
                const MAX_WIDTH = 640;
                const scaleSize = MAX_WIDTH / e.target.width;
                canvas.width = MAX_WIDTH;
                canvas.height = e.target.height * scaleSize;
                //output 320p image
                const ctx = canvas.getContext('2d');
                ctx.drawImage(e.target, 0, 0, canvas.width, canvas.height);
                const srcEncoded = ctx.canvas.toDataURL(e.target, "image/png");
                document.querySelector("#output3").src = srcEncoded;
                
                document.getElementById("h3c").style.display = "inline";

            };
        }
        
        }
    </script>
</body>
</html>